// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{METHOD_ELF, METHOD_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};
// use common::FinancialData;
use common::{CreditMetrics, FinancialData};

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // A default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

    // For example:
    // DEFAULT
    // let input: u32 = 15 * u32::pow(2, 27) + 1;
    // Esempio di input finanziario
    let input = FinancialData {
        monthly_income: 3500,
        monthly_expenses: 1500,
        total_debt: 8000,
        monthly_debt_service: 450,
        requested_loan: 10000,
        loan_duration_months: 36,
    };

    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();


    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover
        .prove(env, METHOD_ELF)
        .unwrap();

    // extract the receipt.
    let receipt = prove_info.receipt;

    // TODO: Implement code for retrieving receipt journal here.

    // For example:
    // let _output: u32 = receipt.journal.decode().unwrap();

    // PROVA Print the input and output to the console 
    // let output: u32 = receipt.journal.decode().unwrap();
    // println!("Input: {input}");
    // println!("Output: {output}");

    // Calcola e stampa le metriche di creditworthiness
    let metrics: CreditMetrics = receipt.journal.decode().unwrap();

    println!("Creditworthiness metrics:");
    println!(
        "  DTI: {:.2}%",
        metrics.dti_bps as f64 / 100.0
    );
    println!(
        "  DSTI: {:.2}%",
        metrics.dsti_bps as f64 / 100.0
    );
    println!(
        "  LTI: {:.2}%",
        metrics.lti_bps as f64 / 100.0
    );
    println!(
        "  Disposable income: €{}",
        metrics.disposable_income
    );

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt
        .verify(METHOD_ID)
        .unwrap();
    print!("Proof verification: VALID");
}
