// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use common::{AssessmentResult, FinancialData};
use methods::{METHOD_ELF, METHOD_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // Financial input data.
    let input = FinancialData {
        monthly_income: 3500,
        monthly_expenses: 1500,
        total_debt: 8000,
        monthly_debt_service: 450,
        requested_loan: 10000,
        loan_duration_months: 36,
        interest_rate_bps: 350,
        dependents: 0,
        age_years: 30,
    };

    // Build the zkVM execution environment.
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Generate the proof for the guest program.
    let prove_info = prover
        .prove(env, METHOD_ELF)
        .unwrap();

    // Extract the receipt.
    let receipt = prove_info.receipt;

    // Decode the public result committed by the guest.
    let result: AssessmentResult = receipt.journal.decode().unwrap();

    println!("Creditworthiness assessment:");
    println!("  Credit score: {}/100", result.credit_score);
    println!("  Eligible: {}", result.eligible);

    print!("  Input SHA-256: ");
    for byte in result.input_hash {
        print!("{byte:02x}");
    }
    println!();

    // Verify the receipt against the expected guest program.
    receipt
        .verify(METHOD_ID)
        .unwrap();

    println!("Proof verification: VALID");
}